plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '1.0.0'
group = 'com.wangand1145'
archivesBaseName = 'tetra_ultimate_material'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://www.cursemaven.com/' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.0'
    implementation fg.deobf("curse.maven:tetra-4006067:6099999")
}

jar {
    manifest {
        attributes([
            "Specification-Title": "tetra_ultimate_material",
            "Specification-Vendor": "you",
            "Specification-Version": "1",
            "Implementation-Title": "tetra_ultimate_material",
            "Implementation-Version": "${version}",
            "Implementation-Vendor": "you"
        ])
    }
}
