repositories {
    maven { url = 'https://maven.blamejared.com/' } // Tetra 和 Mutil 的仓库
    mavenCentral()
}

dependencies {
    // Forge 的 MDK 已经自带的依赖（minecraft、forge、mappings 等）不要动

    // 添加 Tetra 和 Mutil 的依赖
    implementation fg.deobf("se.mickelus.mutil:mutil:1.20.1-6.3.0")
    implementation fg.deobf("se.mickelus.tetra:tetra:1.20.1-6.17.0")
}
