modLoader="javafml"
loaderVersion="47"
license="All Rights Reserved"

[[mods]]
modId="tetra-ultimate-material"
version="1.0.0"
displayName="Tetra Ultimate Material"
authors="You"
description='Adds the Moss Coal material to Tetra.'
